export const AUTH_SESSION_IDLE_SECONDS = 60 * 60 * 24 * 7;
export const AUTH_SESSION_UPDATE_SECONDS = 60 * 60 * 24;
export const AUTH_SESSION_ABSOLUTE_MILLISECONDS = 1000 * 60 * 60 * 24 * 30;

export const AUTH_SESSION_REQUIRED_CODE = "SESSION_REQUIRED" as const;
